### PR TITLE
Clear test result when test code changed #42

### LINKED ISSUE #42: Clear test result when test code changed
Currently, the test result stays when a user changes the actual test code. This could be misleading.

Please clear the test result whenever the test code is changed.

### PR DESCRIPTION
**Pull request by tonytamwk**
Fixed #42

### CODE REVIEW

**Comment by jdneo** [comment]
@tonytamwk Thank you for your contribution.

From the changes, the new behavior will be: clear all the status icon in the Code Lens in the file, if it's modified.

This will fix #42, but I think we could do even better. For example, if the class has two methods: `a()` & `b()`, when `a()` is modified, only the status of `a()` get removed.

To achieve this, we might need to talk with the Java Language Server, send a request with the file uri and the modified range information to it, then let the Language Server to find the method which is being modified and return the name back to the TS client. 

This could be much harder than only changing the TS client part. Would you mind to have a try? Or you can let me finish the Java part, which is fine.

**Comment by tonytamwk** [comment]
@jdneo Thank you for your comments.
Agree that detecting method change is a better approach and will have better usability. Let me try to implement this.

**Comment by jdneo** [comment]
@tonytamwk The way to interact with the Language Server is not well documented so far, so please feel free to ask any question if you have. Meanwhile, I'm also pleased to help you finish the Java part, thanks.

**Comment by jdneo** [comment]
Hi @tonytamwk,

Thank you for your contribution. I proposed a new way to mitigate the #42. More detailed information could be found here: https://github.com/microsoft/vscode-java-test/issues/42#issuecomment-503827198

Thank you again.

**Pull request closed without merging**
