### PR TITLE
build: Update target platform

### LINKED ISSUE #1613: Micronaut 4 Gradle project test execution broken
Generate a sample Micronaut project using [Micronaut Launch](https://micronaut.io/launch/) service with `Micronaut 4.1.1`, `Java 17`, `Gradle`, and `JUnit` selected. Open generated project in VSCode with the [Extension Pack for Java](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-pack) installed. Try to run project tests either via `Test Explorer` or by clicking `Run Test` icons in source editor gutter. No test gets executed and the following error appear in the console:
```
org.junit.platform.commons.JUnitException: TestEngine with ID 'junit-jupiter' failed to discover tests
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:160)
EngineDiscoveryOrchestrator.java:160
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverSafely(EngineDiscoveryOrchestrator.java:132)
EngineDiscoveryOrchestrator.java:132
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discover(EngineDiscoveryOrchestrator.java:107)
EngineDiscoveryOrchestrator.java:107
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discover(EngineDiscoveryOrchestrator.java:78)
EngineDiscoveryOrchestrator.java:78
	at org.junit.platform.launcher.core.DefaultLauncher.discover(DefaultLauncher.java:99)
DefaultLauncher.java:99
	at org.junit.platform.launcher.core.DefaultLauncher.discover(DefaultLauncher.java:77)
DefaultLauncher.java:77
	at org.junit.platform.launcher.core.DelegatingLauncher.discover(DelegatingLauncher.java:42)
DelegatingLauncher.java:42
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.discover(SessionPerRequestLauncher.java:56)
SessionPerRequestLauncher.java:56
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.<init>(JUnit5TestReference.java:46)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestLoader.createUnfilteredTest(JUnit5TestLoader.java:88)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestLoader.createTest(JUnit5TestLoader.java:69)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestLoader.loadTests(JUnit5TestLoader.java:56)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:513)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: org.junit.platform.commons.JUnitException: ClassSelector [className = 'com.example.Mn4gradleTest', classLoader = jdk.internal.loader.ClassLoaders$AppClassLoader@251a69d7] resolution failed
	at org.junit.platform.launcher.listeners.discovery.AbortOnFailureLauncherDiscoveryListener.selectorProcessed(AbortOnFailureLauncherDiscoveryListener.java:39)
AbortOnFailureLauncherDiscoveryListener.java:39
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolveCompletely(EngineDiscoveryRequestResolution.java:103)
EngineDiscoveryRequestResolution.java:103
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.run(EngineDiscoveryRequestResolution.java:83)
EngineDiscoveryRequestResolution.java:83
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolver.resolve(EngineDiscoveryRequestResolver.java:113)
EngineDiscoveryRequestResolver.java:113
	at org.junit.jupiter.engine.discovery.DiscoverySelectorResolver.resolveSelectors(DiscoverySelectorResolver.java:46)
DiscoverySelectorResolver.java:46
	at org.junit.jupiter.engine.JupiterTestEngine.discover(JupiterTestEngine.java:69)
JupiterTestEngine.java:69
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:152)
EngineDiscoveryOrchestrator.java:152
	... 15 more
Caused by: java.lang.NoSuchMethodError: 'java.util.stream.Stream org.junit.platform.commons.support.ReflectionSupport.streamNestedClasses(java.lang.Class, java.util.function.Predicate)'
	at org.junit.jupiter.engine.discovery.ClassSelectorResolver.lambda$toResolution$12(ClassSelectorResolver.java:138)
ClassSelectorResolver.java:138
	at org.junit.platform.engine.support.discovery.SelectorResolver$Match.expand(SelectorResolver.java:668)
SelectorResolver.java:668
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.lambda$enqueueAdditionalSelectors$1(EngineDiscoveryRequestResolution.java:110)
EngineDiscoveryRequestResolution.java:110
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
ForEachOps.java:183
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
ReferencePipeline.java:179
	at java.base/java.util.Collections$2.tryAdvance(Collections.java:4853)
Collections.java:4853
	at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4861)
Collections.java:4861
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
AbstractPipeline.java:509
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
AbstractPipeline.java:499
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
ForEachOps.java:150
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
ForEachOps.java:173
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
AbstractPipeline.java:234
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
ReferencePipeline.java:596
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.enqueueAdditionalSelectors(EngineDiscoveryRequestResolution.java:109)
EngineDiscoveryRequestResolution.java:109
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolveCompletely(EngineDiscoveryRequestResolution.java:95)
EngineDiscoveryRequestResolution.java:95
	... 20 more
```

### PR DESCRIPTION
**Pull request by jdneo**
fix #1613

This will bump the embedded JUnit 5 to 5.10.0.

### CODE REVIEW

**Comment by jdneo** [comment]
@dbalek 

[vscode-java-test-0.40.2023092502.vsix.zip](https://github.com/microsoft/vscode-java-test/files/12712911/vscode-java-test-0.40.2023092502.vsix.zip)

Using this private build and the latest Pre-release of the [vscode-gradle extension](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-gradle), which uses the build server approach should solve the problem. I tested it locally on my machine and it works.

As it is mentioned in https://github.com/microsoft/vscode-java-test/pull/1608, bump to JUnit 5.10.0 might cause the projects using <5.9.x failed to run the tests. I'm not planning to do that at this moment.

From your side, is there any kind of due date or something that need the VS Code Java side to address this issue? If yes, please let me know.

**Comment by dbalek** [comment]
Unfortunatly, tested with the attached [vscode-java-test extension](https://github.com/microsoft/vscode-java-test/files/12712911/vscode-java-test-0.40.2023092502.vsix.zip) and the pre-release (v3.12.2023091801) of the [vscode-gradle extension](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-gradle) I am still getting the same error as in https://github.com/microsoft/vscode-java-test/issues/1613

**Comment by jdneo** [comment]
Sorry forget to mention, you need to clean the workspace cache.

- Open the command palette (Press `F1`)
- Select `Java: Clean Java Language Server Workspace` > `Reload and delete`

**Comment by dbalek** [comment]
Cleaning the workspace cache, still the same result

**Comment by jdneo** [comment]
Could you share your VS Code settings? And maybe a screenshot of the Java Projects View (`F1` >`View: Focus on Java Projects View`)

Another difference is that I'm using Micronaut `4.1.2` instead of `4.1.1`

**Comment by dbalek** [comment]
I have started VSCode with the fresh `--user-data-dir` and `--extensions-dir`, and I have created the new Micronaut 4.1.2 project. So, the `settings.json` is almost empty now:
```
{
    "workbench.startupEditor": "none"
}
```
Still the same result:
screenshot-vscode

**Comment by jdneo** [comment]
There is a node named `Project and External Dependencies` in the Java Projects View, which is a hint that the Gradle project is still imported by the old Gradle importer.

Could you try to clean Java Language Server Workspace again?

More details, see: https://github.com/redhat-developer/vscode-java/issues/3260#issuecomment-1700443681. Sorry for the confusion here.

**Comment by dbalek** [comment]
The node is named `Referenced Libraries (Read-only)` now, otherwise no change...

**Comment by jdneo** [comment]
Still failed to launch tests?

**Comment by dbalek** [comment]
Yes, exactly the same error.

**Comment by jdneo** [comment]
I can reproduce it now on MacOS. Previously I was using Windows, which works fine.

**Comment by yanisderbikov** [comment]
Is still open? Do you need help?

**Comment by jdneo** [comment]
Thank you @yanisderbikov. Since bumping to JUnit 5.10.0 might cause the projects using <= 5.9.x failed to run the tests. I'm not planning to do that at this moment.

**Comment by jdneo** [comment]
More and more users are migrating to 5.10.x

The estimate time for updating the target platform will happen in May.

**Comment by jdneo** [comment]
Fixed in #1722

**Pull request closed without merging**
