### PR TITLE
Add test config field to specify source paths.

### LINKED ISSUE #982: Add a new field in the java.test.config to specify source paths
The [`sourcePaths` key](https://code.visualstudio.com/docs/java/java-debugging) is not being set for the launch configuration created by this extension. Without adding extra source paths to the launch configuration, my VSCode debugger shows `Unknown Source` for all the stack frames that aren’t either found in `src/test/java` or the JDK. The Java Test Runner seems to ignore the debug configurations I have created, [constructing its own instead](https://github.com/microsoft/vscode-java-test/blob/f3fc82f4484ead1dfc2aa5488d2d589090916cdb/src/utils/launchUtils.ts#L56-L69) — shown below.

Is there some other way to inject extra source paths into the launch configurations created by the Java Test Runner, or some other workaround?

With the setting `"java.test.log.level": "verbose"` I see the following Java Test Runner output:
```console
Launching with the following launch configuration: '{
  "name": "Launch Java Tests - 01f5fe",
  "type": "java",
  "request": "launch",
  "mainClass": "org.eclipse.jdt.internal.junit.runner.RemoteTestRunner",
  "projectName": "<redacted>",
  "cwd": "${workspaceFolder}/<redacted>",
  "classPaths": [ <redacted> ],
  "args": [
    "-version",
    "3",
    "-port",
    "51543",
    "-testLoaderClass",
    "org.eclipse.jdt.internal.junit5.runner.JUnit5TestLoader",
    "-loaderpluginname",
    "org.eclipse.jdt.junit5.runtime",
    "-test",
    "<redacted>"
  ],
  "vmArgs": [
    "-ea"
  ],
  "noDebug": false,
  "console": "internalConsole"
}'
```

### PR DESCRIPTION
**Pull request by michael-emmi**
* Fixes #982

### CODE REVIEW

**Comment by jdneo** [comment]
Thank you @michael-emmi for the contribution.

Seems there is some linting errors, would you mind to fix them first?
```
src/utils/launchUtils.ts [26, 13]: Identifier 'moreEntries' is never reassigned; use 'const' instead of 'let'.
src/utils/launchUtils.ts [62, 9]: Identifier 'moreEntries' is never reassigned; use 'const' instead of 'let'.
src/utils/launchUtils.ts [26, 29]: Missing semicolon
src/utils/launchUtils.ts [62, 25]: Missing semicolon
src/utils/launchUtils.ts [26, 13]: expected variable-declaration: 'moreEntries' to have a typedef, src/utils/launchUtils.ts [62, 9]: expected variable-declaration: 'moreEntries' to have a typedef.
```

You can install this [extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-tslint-plugin) to help you detect/fix those TS linting issues

**Comment by michael-emmi** [comment]
> Seems there is some linting errors, would you mind to fix them first?

Oopse, didn’t notice the linter there — fixed now.

**Comment by michael-emmi** [comment]
@jdneo looks ready now, pending your review :-)

**Comment by jdneo** [comment]
Thank you @michael-emmi.

The changes work as expected. While before finally merging it, would you mind to do one more thing to further improve it?

I think we can add the field: `sourcePaths` description in the package.json: https://github.com/microsoft/vscode-java-test/blob/master/package.json#L243-L322.

The purpose of doing that is, when users are editing the setting.json, they will got the completion hint, like following:

Screen Shot 2020-04-30 at 9 44 08 AM

Don't worry about the translation part. I can help to append a commit to do the translation.

**Comment by michael-emmi** [comment]
> I think we can add the field: sourcePaths description in the package.json

@jdneo done

**Pull request merged**
