### PR TITLE
#878 Fix some 'Failed to get workspace folder' error conditions.

### PR DESCRIPTION
**Pull request by rbi**
This fixes my instance of the #878 error. Also the bug is closed it still ocures in my environment. I've described my problem there in comment https://github.com/microsoft/vscode-java-test/issues/878#issuecomment-938396359.

As the bug is already closed I'm not sure if someone will notice my comments there. I also did not want to open another bug.

### CODE REVIEW

**Comment by jdneo** [comment]
Thank you @rbi, will take a look

**Comment by jdneo** [comment]
Actually I'm a little bit confused about this change.

When the URI passed to `workspace.getWorkspaceFolder()` is upper case for the device segment, then it's not working? Did I understand correctly?

**Comment by rbi** [comment]
Yes that seams to be the case. The device segment of the `path` field of the URI must be upper-case for the bug to appear. When you do `toString` on such an uri it shows the drive segment lower-case although it is upper-case in the `path` field.

I've got the idea for the workaround from here:
https://github.com/microsoft/vscode/issues/36221#issuecomment-337670295

This bug should be fixed VS Code 1.18 so that the  `vscode.workspace.getWorkspaceFolder` method can handle upper-case drive segements. In my environment it still is an issue. I do remote development on a remote Windows. So maybe the `vscode.workspace.getWorkspaceFolder` is re-implemented somewhere in the remote development extensions where they implemented the bug a second time? If so it may should be fixed there.

Other specialties about my system:
* The VS-Code GUI is running on a Linux machine connecting to a Windows VM with a UI session remotely.
* I start the Windows sshd not via service but manually in a Powershell window as I want to be able to start GUI programs from VS-Code.

**Comment by jdneo** [comment]
@rbi seems the upstream issue has been fixed. Is this PR still valid?

**Comment by rbi** [comment]
I haven't tried the fix yet but as they could reproduce the problem I guess it should work now. At least it seams to be no problem in the vscode-java-test plugin as you said.

**Pull request closed without merging**
