### PR TITLE
feat: run all tests from active editor

### PR DESCRIPTION
**Pull request by anothernode**
Hi!

I managed to create a command that runs all tests from the currently opened file in the active editor, thus addressing the first part of #531.

I'm completely new to VS Code Extension development and almost completely new to JavaScript/TypeScript and I'm pretty sure there's a lot of room for improvement in terms of code style and robustness. So if you folks see any problems with the code I'd be happy to revise the PR according to your guidance :)

### CODE REVIEW

**Comment by anothernode** [comment]
I don't understand why the checks are failing. When I run `npm run test` locally, I don't see any failing tests.

Let me know if there's anything I can do to help getting the checks to pass.

**Comment by jdneo** [comment]
Thank you @anothernode, 

I'm thinking that if we can use just one new command to achieve all, for example:

1. if focus is a java file/folder in file explorer, run all the test in the classes/packages -> similar to run test from test explorer
2. if focus is in editor, and the cursor belongs to a class scope, run the tests in the class.
3. if focus is in editor, and the cursor belongs to a method scope, run this test method.

The 2 & 3 might be able to achieved by get the covering AST node, which could be queried from the Java Language Server. Let me think more about the solution, and update to you later.

**Comment by anothernode** [comment]
Thanks for your feedback @jdneo!

I agree that your suggestion would be a more comprehensive and nicer solution. If I find the time I'll try and work out the details about how to query the Java Language Server for figuring out in which scope the cursor currently is and how to make the distinction between 1) focus in explorer and 2/3) focus in editor.

If you can give any further hints on how to approach this, example code, docs etc. I'd very much appreciate any advice.

**Comment by anothernode** [comment]
Thankfully this was implemented in a nicer way by @jdneo

**Comment by jdneo** [comment]
@anothernode Thank you for your contribution.

**Pull request closed without merging**
