### PR TITLE
feat: Add codicon in the labels of test items

### PR DESCRIPTION
**Pull request by jdneo**
Signed-off-by: Sheng Chen <sheche@microsoft.com>

### CODE REVIEW

**Comment by jdneo** [comment]
Render result:

#### When no results available
##### New
new_no_result

##### Old
old_no_result

#### Results available
##### New
new

##### Old
old

**Review by Eskibear — APPROVED** [review]
looks great

**Comment by jdneo** [comment]
Not sure if users would feel that the UI looks a little bit complex after adding the codicons.

Anyway, let's merge it first and see if we can get some feedbacks from pre-release channel. :)

**Comment by Eskibear** [comment]
I myself don't feel crowded at all. Because the codicon icons can provide further information of the node type, i.e. package/type/method, that I can easily tell the levels...

**Comment by matter-it-does** [comment]
#1453

**Pull request merged**
